{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-deploy
  labels:
    app: {{ $.Release.Name }}-{{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .containerPort }}
              protocol: TCP
          {{- if .command }}
    command:
      {{- toYaml .command | nindent 14 }}
    {{- end }}
---
{{- end }}

