{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-svc
  labels:
    app: {{ $.Release.Name }}-{{ .name }}
spec:
  selector:
    app: {{ $.Release.Name }}-{{ .name }}
  ports:
    - port: 80
      targetPort: {{ .containerPort }}
      protocol: TCP
  type: ClusterIP

---
{{- end }}
